# Lug'atlar
[[translations]]
source = "Infiltrating"
target = "Kirish"
description = ""

[[translations]]
source = "Debug"
target = "Taftish"
description = ""

[[translations]]
source = "Sensor"
target = "Sensor"
description = ""

[[translations]]
source = "Multithread"
target = "Ko'p oqimli"
description = "Ko'p oqimli ishlov berish jarayoni haqida atama."

[[translations]]
source = "Single thread"
target = "Bir oqimli"
description = "Bitta oqim bilan ishlaydigan jarayon."

[[translations]]
source = "Concurrency"
target = "Parallel ishlash"
description = "Bir nechta vazifalarni bir vaqtda boshqarish."
